// ──────────────────────────────────────────────
// DATA — recipes, meal plan template, AI responses
// ──────────────────────────────────────────────

const SAMPLE_RECIPES = [
  {
    id: 1,
    icon: '🥗',
    name: 'Garlic Broccoli Frittata',
    time: '25 min',
    cal: 320,
    tags: ['Vegetarian', 'High Protein'],
    ingredients: ['2 cups broccoli florets', '6 large eggs', '3 cloves garlic, minced', '½ cup shredded cheddar', '2 tbsp olive oil', 'Salt & pepper to taste'],
    instructions: [
      'Preheat oven to 375°F.',
      'Sauté garlic in olive oil over medium heat for 1 minute until fragrant.',
      'Add broccoli and cook 4–5 minutes until tender-crisp.',
      'Whisk eggs with salt and pepper, then pour over the vegetables.',
      'Top with shredded cheddar.',
      'Cook on stovetop 3 minutes until edges set, then bake 10–12 minutes until golden and puffed.',
      'Slice into wedges and serve warm.',
    ],
    nutrition: { protein: 24, carbs: 10, fat: 22, fiber: 12 },
  },
  {
    id: 2,
    icon: '🍲',
    name: 'Tomato Basil Soup',
    time: '30 min',
    cal: 210,
    tags: ['Vegan', 'Low-Cal'],
    ingredients: ['6 ripe tomatoes, chopped', '1 cup fresh basil leaves', '4 cloves garlic', '1 large onion, diced', '2 tbsp olive oil', '3 cups veggie stock'],
    instructions: [
      'Heat olive oil in a large pot over medium heat.',
      'Sauté diced onion until translucent, about 5 minutes.',
      'Add garlic and cook 1 minute more.',
      'Add chopped tomatoes and veggie stock. Bring to a boil.',
      'Reduce heat and simmer 20 minutes.',
      'Blend until smooth using an immersion blender.',
      'Stir in fresh basil, season to taste, and serve.',
    ],
    nutrition: { protein: 5, carbs: 28, fat: 8, fiber: 18 },
  },
  {
    id: 3,
    icon: '🍜',
    name: 'Veggie Stir-Fry Noodles',
    time: '20 min',
    cal: 390,
    tags: ['Vegan', 'Quick'],
    ingredients: ['200g rice noodles', '2 cups broccoli florets', '4 cloves garlic, minced', '3 tbsp soy sauce', '2 tbsp sesame oil', '1 tsp fresh ginger, grated'],
    instructions: [
      'Cook noodles according to package directions. Drain and set aside.',
      'Heat sesame oil in a wok over high heat.',
      'Add garlic and ginger, stir-fry 30 seconds.',
      'Add broccoli and cook 4 minutes, tossing frequently.',
      'Add noodles and soy sauce, toss to combine.',
      'Cook 2 more minutes until everything is heated through.',
      'Serve immediately garnished with sesame seeds.',
    ],
    nutrition: { protein: 12, carbs: 58, fat: 14, fiber: 10 },
  },
  {
    id: 4,
    icon: '🥚',
    name: 'Shakshuka',
    time: '35 min',
    cal: 280,
    tags: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['1 can crushed tomatoes (400g)', '4 large eggs', '3 cloves garlic, minced', '1 tsp ground cumin', '1 tsp smoked paprika', '1 medium onion, diced'],
    instructions: [
      'Heat oil in a wide skillet over medium heat.',
      'Sauté onion until translucent, about 5 minutes.',
      'Add garlic, cumin, and paprika. Cook 1 minute.',
      'Pour in crushed tomatoes and simmer 10 minutes until thickened.',
      'Make 4 wells in the sauce and crack an egg into each.',
      'Cover and cook 8–10 minutes until whites are set but yolks remain runny.',
      'Garnish with fresh herbs and serve with crusty bread.',
    ],
    nutrition: { protein: 18, carbs: 22, fat: 15, fiber: 14 },
  },
  {
    id: 5,
    icon: '🥙',
    name: 'Caprese Flatbread',
    time: '15 min',
    cal: 350,
    tags: ['Vegetarian', 'Quick'],
    ingredients: ['2 flatbreads', '3 ripe tomatoes, sliced', '200g fresh mozzarella, sliced', '½ cup fresh basil leaves', '2 tbsp olive oil', '1 tbsp balsamic glaze'],
    instructions: [
      'Preheat oven to 400°F.',
      'Brush flatbreads generously with olive oil.',
      'Layer sliced tomatoes and mozzarella alternately.',
      'Bake 10–12 minutes until cheese is melted and edges are golden.',
      'Drizzle with balsamic glaze.',
      'Top with fresh basil leaves and serve immediately.',
    ],
    nutrition: { protein: 16, carbs: 32, fat: 18, fiber: 8 },
  },
  {
    id: 6,
    icon: '🫕',
    name: 'Chickpea Veggie Curry',
    time: '40 min',
    cal: 420,
    tags: ['Vegan', 'High Protein'],
    ingredients: ['1 can chickpeas (400g), drained', '1 can crushed tomatoes (400g)', '1 can coconut milk (400ml)', '4 cloves garlic, minced', '1 tsp fresh ginger', '2 cups baby spinach', '2 tsp ground cumin'],
    instructions: [
      'Heat oil in a large pot over medium heat.',
      'Add garlic and ginger, cook 1 minute until fragrant.',
      'Stir in cumin and a pinch of turmeric.',
      'Add chickpeas, crushed tomatoes, and coconut milk.',
      'Bring to a boil, then simmer 20 minutes.',
      'Stir in spinach until wilted, about 2 minutes.',
      'Season generously and serve over rice or with naan.',
    ],
    nutrition: { protein: 16, carbs: 48, fat: 18, fiber: 22 },
  },
  {
    id: 7,
    icon: '🥩',
    name: 'Lemon Herb Chicken',
    time: '35 min',
    cal: 380,
    tags: ['High Protein', 'Gluten-Free'],
    ingredients: ['2 chicken breasts', '1 lemon, zested and juiced', '3 cloves garlic, minced', '2 tbsp olive oil', '1 tsp dried oregano', '1 tsp dried thyme'],
    instructions: [
      'Pound chicken breasts to an even thickness.',
      'Whisk together lemon juice, zest, garlic, olive oil, oregano, and thyme.',
      'Marinate chicken in the mixture for at least 15 minutes.',
      'Heat a skillet over medium-high heat.',
      'Cook chicken 6–7 minutes per side until golden and cooked through.',
      'Rest for 5 minutes before slicing.',
      'Serve with roasted vegetables or a simple salad.',
    ],
    nutrition: { protein: 42, carbs: 4, fat: 20, fiber: 4 },
  },
  {
    id: 8,
    icon: '🍱',
    name: 'Teriyaki Salmon Bowl',
    time: '30 min',
    cal: 490,
    tags: ['High Protein', 'Quick'],
    ingredients: ['2 salmon fillets (150g each)', '1 cup sushi rice', '3 tbsp soy sauce', '1 tbsp honey', '1 tsp sesame oil', '1 cup edamame', '1 avocado, sliced'],
    instructions: [
      'Cook sushi rice according to package directions.',
      'Mix soy sauce, honey, and sesame oil for the teriyaki glaze.',
      'Brush salmon fillets generously with the glaze.',
      'Sear salmon in a hot non-stick pan 4 minutes per side.',
      'Brush with more glaze while cooking.',
      'Assemble bowls with rice, salmon, edamame, and avocado.',
      'Drizzle with remaining glaze and garnish with sesame seeds.',
    ],
    nutrition: { protein: 38, carbs: 44, fat: 22, fiber: 16 },
  },
  {
    id: 9,
    icon: '🥦',
    name: 'Miso Glazed Tofu',
    time: '25 min',
    cal: 310,
    tags: ['Vegan', 'High Protein'],
    ingredients: ['400g firm tofu, pressed and cubed', '2 tbsp white miso paste', '1 tbsp soy sauce', '1 tbsp rice vinegar', '1 tsp sesame oil', '2 cups bok choy'],
    instructions: [
      'Press tofu for at least 10 minutes to remove excess water.',
      'Whisk together miso, soy sauce, rice vinegar, and sesame oil.',
      'Toss tofu cubes in half the miso glaze.',
      'Bake at 400°F for 20 minutes, flipping halfway, until crispy.',
      'Steam bok choy for 3 minutes until just tender.',
      'Drizzle remaining glaze over tofu and bok choy.',
      'Serve over steamed rice with sesame seeds.',
    ],
    nutrition: { protein: 22, carbs: 18, fat: 16, fiber: 12 },
  },
  {
    id: 10,
    icon: '🌮',
    name: 'Black Bean Tacos',
    time: '20 min',
    cal: 340,
    tags: ['Vegan', 'Quick'],
    ingredients: ['1 can black beans (400g)', '8 small corn tortillas', '1 cup shredded purple cabbage', '1 avocado, diced', '½ cup salsa', '1 lime, juiced', '1 tsp cumin'],
    instructions: [
      'Drain and rinse black beans.',
      'Heat beans in a pan with cumin and a splash of water, 3–4 minutes.',
      'Warm tortillas directly over a gas flame or in a dry pan.',
      'Mash beans slightly with a fork.',
      'Assemble tacos with beans, cabbage, and avocado.',
      'Top with salsa and a squeeze of lime.',
      'Serve immediately with extra lime wedges.',
    ],
    nutrition: { protein: 14, carbs: 52, fat: 12, fiber: 28 },
  },
  {
    id: 11,
    icon: '🍝',
    name: 'Creamy Mushroom Pasta',
    time: '30 min',
    cal: 460,
    tags: ['Vegetarian', 'Comfort Food'],
    ingredients: ['300g pappardelle pasta', '300g mixed mushrooms, sliced', '3 cloves garlic', '½ cup heavy cream', '¼ cup parmesan, grated', '2 tbsp butter'],
    instructions: [
      'Cook pasta in well-salted boiling water until al dente. Reserve 1 cup pasta water.',
      'Melt butter in a large skillet over high heat.',
      'Add mushrooms in a single layer — do not stir for 2 minutes to get a good sear.',
      'Add garlic and cook 1 minute more.',
      'Pour in cream and bring to a simmer.',
      'Toss in drained pasta with a splash of pasta water.',
      'Finish with parmesan, season generously, and serve immediately.',
    ],
    nutrition: { protein: 18, carbs: 56, fat: 22, fiber: 8 },
  },
  {
    id: 12,
    icon: '🥬',
    name: 'Greek Lentil Salad',
    time: '15 min',
    cal: 290,
    tags: ['Vegan', 'Low-Cal', 'High Protein'],
    ingredients: ['1 can green lentils (400g), drained', '1 cucumber, diced', '200g cherry tomatoes, halved', '½ red onion, finely sliced', '100g kalamata olives', '3 tbsp olive oil', '2 tbsp red wine vinegar'],
    instructions: [
      'Drain and rinse lentils thoroughly.',
      'Dice cucumber and halve cherry tomatoes.',
      'Thinly slice red onion.',
      'Whisk together olive oil, red wine vinegar, salt, and oregano.',
      'Combine lentils, cucumber, tomatoes, onion, and olives in a bowl.',
      'Pour over dressing and toss well.',
      'Let sit 5 minutes before serving for flavors to meld.',
    ],
    nutrition: { protein: 16, carbs: 34, fat: 12, fiber: 24 },
  },
];

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const MEAL_SLOTS = ['breakfast', 'lunch', 'dinner'];

const AI_RESPONSES = [
  "Great question! You can reduce sodium by using low-sodium soy sauce or replacing it entirely with coconut aminos. Fresh herbs and lemon juice can also add brightness without extra salt. 🌿",
  "For a heavy cream substitute, try full-fat coconut milk — it adds creaminess with a subtle sweetness that works beautifully in savory dishes. Greek yogurt is another excellent option for soups and sauces.",
  "With pantry staples, you can make a delicious pasta aglio e olio (garlic + olive oil + pasta), a hearty lentil soup, or even a simple fried rice if you have leftover grains. 🧄",
  "For meal prep, cook the full batch on Sunday and store in airtight containers. Most cooked dishes keep well for 4–5 days in the fridge. I'd recommend keeping sauces separate until serving to maintain texture!",
  "That's a great ingredient combination! I'd suggest roasting your vegetables first to develop deeper flavor before combining them — it adds richness without extra fat. 🔥",
  "For a healthier swap, try using cauliflower rice instead of white rice — it cuts the carbs significantly while keeping the dish filling. Your favorite stir-fry sauce works just the same! 🥦",
];